# Generated by Django 4.1.4 on 2022-12-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='bookimages/'),
        ),
    ]
